[package]
name = "golos-lib"
version = "0.9.0"
license = "MIT"
repository = "https://github.com/golos-blockchain/golos-lib"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.53"
aes = "0.7.5"
block-modes = "0.8.1"
num-bigint = "0.4"
